# .pre-commit-config.yaml file stored in the root of backend
# you find the full pre-commit-tools docu under:
# https://pre-commit.com/
repos:
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--check, --diff, --config=pyproject.toml]
        language_version: python3.11
        stages: [push]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: [--profile, black, --check, --diff, --sp=./ai_apps/]
        language_version: python3.11
        stages: [push]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.5.3'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
    hooks:
      - id: pyupgrade
        args: [ --py311-plus ]
        language_version: python3.11
        stages: [ push ]